### ISSUE TITLE
HGFS fails to compile on kernel 3.16.2

### ISSUE THREAD

**Issue by liayn** [rasa/vmware-tools-patches#11]
```
/tmp/modconfig-koK1AB/vmhgfs-only/link.c: In function ‘HgfsReadlink’:
/tmp/modconfig-koK1AB/vmhgfs-only/link.c:186:10: error: implicit declaration of function ‘vfs_readlink’ [-Werror=implicit-function-declaration]
          error = vfs_readlink(dentry, buffer, buflen, fileName);

....

/tmp/modconfig-goW7eY/vmhgfs-only/file.c: In function ‘HgfsAioRead’:
/tmp/modconfig-goW7eY/vmhgfs-only/file.c:791:4: error: implicit declaration of function ‘generic_file_aio_read’ [-Werror=implicit-function-declaration]
    result = generic_file_aio_read(iocb, iov, numSegs, offset);
    ^
/tmp/modconfig-goW7eY/vmhgfs-only/file.c: In function ‘HgfsAioWrite’:
/tmp/modconfig-goW7eY/vmhgfs-only/file.c:863:4: error: implicit declaration of function ‘generic_file_aio_write’ [-Werror=implicit-function-declaration]
    result = generic_file_aio_write(iocb, iov, numSegs, offset);
```

Fedora 20
Kernel: 3.16.2

**Comment by diablo2424** [comment]
@liayn How can I apply the patched you linked above?

"Fixes:
https://github.com/skroll/open-vm-tools-dkms/blob/master/0007-Fix-vmhgfs-module-on-kernels-3.16.patch
https://github.com/skroll/open-vm-tools-dkms/blob/master/0008-Fix-segfault-in-vmhgfs.patch

Second patch more or less reverts the first one and does some other things."

I opened those links, but am unsure as to what to do with the pasted text...

**Comment by liayn** [comment]
Have a look at this repo here. The links above are obsolete. The correct patches are available in this repo.

Take a look  at http://jungels.net/articles/diff-patch-ten-minutes.html for instance, on how  to apply patches.

**Comment by diablo2424** [comment]
Okay, thank you for the info, I'll follow the Wiki and see if I can get the newer patch from this repo downloaded and installed.  This patching is all new to me...
