### ISSUE TITLE
Error in compiling tools on Ubuntu 12.04 x64 on VMWare Workstation 11.1.2

### ISSUE THREAD

**Issue by thedevilfish** [rasa/vmware-tools-patches#69]
Hello,

Having trouble with compilation of tools on Ubuntu 12.0.4 x64 running VMWare Workstation 11.1.2.
Here are the error messages. I am using tools version: 9.9.3. Could you help?

```
Using kernel build system.
make: Entering directory `/tmp/modconfig-PnqLju/vmci-only'
/usr/bin/make -C /lib/modules/3.8.0-44-generic/build/include/.. SUBDIRS=$PWD SRCROOT=$PWD/. \
	  MODULEBUILDDIR= modules
make[1]: Entering directory `/usr/src/linux-headers-3.8.0-44-generic'
/usr/src/linux-headers-3.8.0-44-generic/arch/x86/Makefile:109: CONFIG_X86_X32 enabled but no binutils support
  CC [M]  /tmp/modconfig-PnqLju/vmci-only/linux/driver.o
  CC [M]  /tmp/modconfig-PnqLju/vmci-only/linux/vmciKernelIf.o
/tmp/modconfig-PnqLju/vmci-only/linux/driver.c:131:4: error: implicit declaration of function ‘__devexit_p’ [-Werror=implicit-function-declaration]
/tmp/modconfig-PnqLju/vmci-only/linux/driver.c:131:4: error: initializer element is not constant
/tmp/modconfig-PnqLju/vmci-only/linux/driver.c:131:4: error: (near initialization for ‘vmci_driver.remove’)
/tmp/modconfig-PnqLju/vmci-only/linux/driver.c:1749:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘vmci_probe_device’
/tmp/modconfig-PnqLju/vmci-only/linux/driver.c:1980:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘vmci_remove_device’
/tmp/modconfig-PnqLju/vmci-only/linux/driver.c:123:12: warning: ‘vmci_probe_device’ used but never defined [enabled by default]
/tmp/modconfig-PnqLju/vmci-only/linux/driver.c:125:13: warning: ‘vmci_remove_device’ used but never defined [enabled by default]
/tmp/modconfig-PnqLju/vmci-only/linux/driver.c:2061:1: warning: ‘vmci_interrupt’ defined but not used [-Wunused-function]
/tmp/modconfig-PnqLju/vmci-only/linux/driver.c:2135:1: warning: ‘vmci_interrupt_bm’ defined but not used [-Wunused-function]
/tmp/modconfig-PnqLju/vmci-only/linux/driver.c:187:19: warning: ‘notification_base’ defined but not used [-Wunused-variable]
/tmp/modconfig-PnqLju/vmci-only/linux/driver.c:1712:1: warning: ‘vmci_enable_msix’ defined but not used [-Wunused-function]
cc1: some warnings being treated as errors
make[2]: *** [/tmp/modconfig-PnqLju/vmci-only/linux/driver.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [_module_/tmp/modconfig-PnqLju/vmci-only] Error 2
make[1]: Leaving directory `/usr/src/linux-headers-3.8.0-44-generic'
make: *** [vmci.ko] Error 2
make: Leaving directory `/tmp/modconfig-PnqLju/vmci-only'

The communication service is used in addition to the standard communication 
between the guest and the host.  The rest of the software provided by VMware 
Tools is designed to work independently of this feature.
If you wish to have the VMCI feature, you can install the driver by running 
vmware-config-tools.pl again after making sure that gcc, binutils, make and the
kernel sources for your running kernel are installed on your machine. These 
packages are available on your distribution's installation CD.
[ Press Enter key to continue ] 

Using kernel build system.
make: Entering directory `/tmp/modconfig-1bJVvI/vmci-only'
/usr/bin/make -C /lib/modules/3.8.0-44-generic/build/include/.. SUBDIRS=$PWD SRCROOT=$PWD/. \
	  MODULEBUILDDIR= modules
make[1]: Entering directory `/usr/src/linux-headers-3.8.0-44-generic'
/usr/src/linux-headers-3.8.0-44-generic/arch/x86/Makefile:109: CONFIG_X86_X32 enabled but no binutils support
  CC [M]  /tmp/modconfig-1bJVvI/vmci-only/linux/driver.o
  CC [M]  /tmp/modconfig-1bJVvI/vmci-only/linux/vmciKernelIf.o
/tmp/modconfig-1bJVvI/vmci-only/linux/driver.c:131:4: error: implicit declaration of function ‘__devexit_p’ [-Werror=implicit-function-declaration]
/tmp/modconfig-1bJVvI/vmci-only/linux/driver.c:131:4: error: initializer element is not constant
/tmp/modconfig-1bJVvI/vmci-only/linux/driver.c:131:4: error: (near initialization for ‘vmci_driver.remove’)
/tmp/modconfig-1bJVvI/vmci-only/linux/driver.c:1749:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘vmci_probe_device’
/tmp/modconfig-1bJVvI/vmci-only/linux/driver.c:1980:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘vmci_remove_device’
/tmp/modconfig-1bJVvI/vmci-only/linux/driver.c:123:12: warning: ‘vmci_probe_device’ used but never defined [enabled by default]
/tmp/modconfig-1bJVvI/vmci-only/linux/driver.c:125:13: warning: ‘vmci_remove_device’ used but never defined [enabled by default]
/tmp/modconfig-1bJVvI/vmci-only/linux/driver.c:2061:1: warning: ‘vmci_interrupt’ defined but not used [-Wunused-function]
/tmp/modconfig-1bJVvI/vmci-only/linux/driver.c:2135:1: warning: ‘vmci_interrupt_bm’ defined but not used [-Wunused-function]
/tmp/modconfig-1bJVvI/vmci-only/linux/driver.c:187:19: warning: ‘notification_base’ defined but not used [-Wunused-variable]
/tmp/modconfig-1bJVvI/vmci-only/linux/driver.c:1712:1: warning: ‘vmci_enable_msix’ defined but not used [-Wunused-function]
cc1: some warnings being treated as errors
make[2]: *** [/tmp/modconfig-1bJVvI/vmci-only/linux/driver.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [_module_/tmp/modconfig-1bJVvI/vmci-only] Error 2
make[1]: Leaving directory `/usr/src/linux-headers-3.8.0-44-generic'
make: *** [vmci.ko] Error 2
make: Leaving directory `/tmp/modconfig-1bJVvI/vmci-only'

The VM communication interface socket family is used in conjunction with the VM
communication interface to provide a new communication path among guests and 
host.  The rest of this software provided by VMware Tools is designed to work 
independently of this feature.  If you wish to have the VSOCK feature  you can 
install the driver by running vmware-config-tools.pl again after making sure 
that gcc, binutils, make and the kernel sources for your running kernel are 
installed on your machine. These packages are available on your distribution's 
installation CD.
[ Press the Enter key to continue.] 

The module vmxnet3 has already been installed on this system by another package
but has been marked for clobbering and will be overridden.

Using kernel build system.
make: Entering directory `/tmp/modconfig-6qFIgP/vmxnet3-only'
/usr/bin/make -C /lib/modules/3.8.0-44-generic/build/include/.. SUBDIRS=$PWD SRCROOT=$PWD/. \
	  MODULEBUILDDIR= modules
make[1]: Entering directory `/usr/src/linux-headers-3.8.0-44-generic'
/usr/src/linux-headers-3.8.0-44-generic/arch/x86/Makefile:109: CONFIG_X86_X32 enabled but no binutils support
  CC [M]  /tmp/modconfig-6qFIgP/vmxnet3-only/vmxnet3_ethtool.o
  CC [M]  /tmp/modconfig-6qFIgP/vmxnet3-only/vmxnet3_drv.o
  CC [M]  /tmp/modconfig-6qFIgP/vmxnet3-only/vmxnet3_shm.o
  LD [M]  /tmp/modconfig-6qFIgP/vmxnet3-only/vmxnet3.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /tmp/modconfig-6qFIgP/vmxnet3-only/vmxnet3.mod.o
  LD [M]  /tmp/modconfig-6qFIgP/vmxnet3-only/vmxnet3.ko
make[1]: Leaving directory `/usr/src/linux-headers-3.8.0-44-generic'
/usr/bin/make -C $PWD SRCROOT=$PWD/. \
	  MODULEBUILDDIR= postbuild
make[1]: Entering directory `/tmp/modconfig-6qFIgP/vmxnet3-only'
make[1]: `postbuild' is up to date.
make[1]: Leaving directory `/tmp/modconfig-6qFIgP/vmxnet3-only'
cp -f vmxnet3.ko ./../vmxnet3.o
make: Leaving directory `/tmp/modconfig-6qFIgP/vmxnet3-only'

The module pvscsi has already been installed on this system by another package 
but has been marked for clobbering and will be overridden.

Using kernel build system.
make: Entering directory `/tmp/modconfig-CV4m90/pvscsi-only'
/usr/bin/make -C /lib/modules/3.8.0-44-generic/build/include/.. SUBDIRS=$PWD SRCROOT=$PWD/. \
	  MODULEBUILDDIR= modules
make[1]: Entering directory `/usr/src/linux-headers-3.8.0-44-generic'
/usr/src/linux-headers-3.8.0-44-generic/arch/x86/Makefile:109: CONFIG_X86_X32 enabled but no binutils support
  CC [M]  /tmp/modconfig-CV4m90/pvscsi-only/pvscsi.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /tmp/modconfig-CV4m90/pvscsi-only/pvscsi.mod.o
  LD [M]  /tmp/modconfig-CV4m90/pvscsi-only/pvscsi.ko
make[1]: Leaving directory `/usr/src/linux-headers-3.8.0-44-generic'
/usr/bin/make -C $PWD SRCROOT=$PWD/. \
	  MODULEBUILDDIR= postbuild
make[1]: Entering directory `/tmp/modconfig-CV4m90/pvscsi-only'
make[1]: `postbuild' is up to date.
make[1]: Leaving directory `/tmp/modconfig-CV4m90/pvscsi-only'
cp -f pvscsi.ko ./../pvscsi.o
make: Leaving directory `/tmp/modconfig-CV4m90/pvscsi-only'

The module vmmemctl has already been installed on this system by another 
package but has been marked for clobbering and will be overridden.

Using kernel build system.
make: Entering directory `/tmp/modconfig-7dMUhd/vmmemctl-only'
/usr/bin/make -C /lib/modules/3.8.0-44-generic/build/include/.. SUBDIRS=$PWD SRCROOT=$PWD/. \
	  MODULEBUILDDIR= modules
make[1]: Entering directory `/usr/src/linux-headers-3.8.0-44-generic'
/usr/src/linux-headers-3.8.0-44-generic/arch/x86/Makefile:109: CONFIG_X86_X32 enabled but no binutils support
  CC [M]  /tmp/modconfig-7dMUhd/vmmemctl-only/backdoorGcc64.o
  CC [M]  /tmp/modconfig-7dMUhd/vmmemctl-only/backdoor_balloon.o
  CC [M]  /tmp/modconfig-7dMUhd/vmmemctl-only/kernelStubsLinux.o
  CC [M]  /tmp/modconfig-7dMUhd/vmmemctl-only/os.o
  CC [M]  /tmp/modconfig-7dMUhd/vmmemctl-only/vmballoon.o
  LD [M]  /tmp/modconfig-7dMUhd/vmmemctl-only/vmmemctl.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /tmp/modconfig-7dMUhd/vmmemctl-only/vmmemctl.mod.o
  LD [M]  /tmp/modconfig-7dMUhd/vmmemctl-only/vmmemctl.ko
make[1]: Leaving directory `/usr/src/linux-headers-3.8.0-44-generic'
/usr/bin/make -C $PWD SRCROOT=$PWD/. \
	  MODULEBUILDDIR= postbuild
make[1]: Entering directory `/tmp/modconfig-7dMUhd/vmmemctl-only'
make[1]: `postbuild' is up to date.
make[1]: Leaving directory `/tmp/modconfig-7dMUhd/vmmemctl-only'
cp -f vmmemctl.ko ./../vmmemctl.o
make: Leaving directory `/tmp/modconfig-7dMUhd/vmmemctl-only'

The VMware Host-Guest Filesystem allows for shared folders between the host OS 
and the guest OS in a Fusion or Workstation virtual environment.  Do you wish 
to enable this feature? [yes] 

Using kernel build system.
make: Entering directory `/tmp/modconfig-uSijee/vmhgfs-only'
/usr/bin/make -C /lib/modules/3.8.0-44-generic/build/include/.. SUBDIRS=$PWD SRCROOT=$PWD/. \
	  MODULEBUILDDIR= modules
make[1]: Entering directory `/usr/src/linux-headers-3.8.0-44-generic'
/usr/src/linux-headers-3.8.0-44-generic/arch/x86/Makefile:109: CONFIG_X86_X32 enabled but no binutils support
  CC [M]  /tmp/modconfig-uSijee/vmhgfs-only/backdoorGcc64.o
  CC [M]  /tmp/modconfig-uSijee/vmhgfs-only/backdoor.o
  CC [M]  /tmp/modconfig-uSijee/vmhgfs-only/bdhandler.o
  CC [M]  /tmp/modconfig-uSijee/vmhgfs-only/cpName.o
  CC [M]  /tmp/modconfig-uSijee/vmhgfs-only/cpNameLinux.o
  CC [M]  /tmp/modconfig-uSijee/vmhgfs-only/cpNameLite.o
  CC [M]  /tmp/modconfig-uSijee/vmhgfs-only/dentry.o
  CC [M]  /tmp/modconfig-uSijee/vmhgfs-only/dir.o
  CC [M]  /tmp/modconfig-uSijee/vmhgfs-only/file.o
  CC [M]  /tmp/modconfig-uSijee/vmhgfs-only/filesystem.o
  CC [M]  /tmp/modconfig-uSijee/vmhgfs-only/fsutil.o
  CC [M]  /tmp/modconfig-uSijee/vmhgfs-only/hgfsBd.o
  CC [M]  /tmp/modconfig-uSijee/vmhgfs-only/hgfsEscape.o
  CC [M]  /tmp/modconfig-uSijee/vmhgfs-only/hgfsUtil.o
  CC [M]  /tmp/modconfig-uSijee/vmhgfs-only/inode.o
  CC [M]  /tmp/modconfig-uSijee/vmhgfs-only/link.o
  CC [M]  /tmp/modconfig-uSijee/vmhgfs-only/message.o
  CC [M]  /tmp/modconfig-uSijee/vmhgfs-only/module.o
  CC [M]  /tmp/modconfig-uSijee/vmhgfs-only/page.o
  CC [M]  /tmp/modconfig-uSijee/vmhgfs-only/request.o
  CC [M]  /tmp/modconfig-uSijee/vmhgfs-only/rpcout.o
  CC [M]  /tmp/modconfig-uSijee/vmhgfs-only/stubs.o
  CC [M]  /tmp/modconfig-uSijee/vmhgfs-only/super.o
  CC [M]  /tmp/modconfig-uSijee/vmhgfs-only/transport.o
  CC [M]  /tmp/modconfig-uSijee/vmhgfs-only/kernelStubsLinux.o
  LD [M]  /tmp/modconfig-uSijee/vmhgfs-only/vmhgfs.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /tmp/modconfig-uSijee/vmhgfs-only/vmhgfs.mod.o
  LD [M]  /tmp/modconfig-uSijee/vmhgfs-only/vmhgfs.ko
make[1]: Leaving directory `/usr/src/linux-headers-3.8.0-44-generic'
/usr/bin/make -C $PWD SRCROOT=$PWD/. \
	  MODULEBUILDDIR= postbuild
make[1]: Entering directory `/tmp/modconfig-uSijee/vmhgfs-only'
make[1]: `postbuild' is up to date.
make[1]: Leaving directory `/tmp/modconfig-uSijee/vmhgfs-only'
cp -f vmhgfs.ko ./../vmhgfs.o
make: Leaving directory `/tmp/modconfig-uSijee/vmhgfs-only'
```

**Comment by putztzu** [comment]
How did you attempt to compile and install?

Read the docs... Individual scripts are provided that do specific things and there is a master script called "patched-open-vm-tools.sh" that ensures you have the required prerequisites installed on your machine, downloads either the latest or a specified Tools and installs. That master script is the recommended way to update the Tools on your system.

**Comment by dragon788** [comment]
@thedevilfish Have you tried this again recently, and is it still an issue?

**Comment by thedevilfish** [comment]
Yes, I looks like it got fixed with the recent vmware tools and patches. You may close it.
