### ISSUE TITLE
Error compiling vmhgfs on 3.12

### ISSUE THREAD

**Issue by joefiorini** [rasa/vmware-tools-patches#2]
I'm having trouble getting vmhgfs to compile with the provided patch on the 3.12 kernel. I'm trying to build on Archlinux. Here's the output I'm getting:

```
In file included from /tmp/modconfig-cAothp/vmhgfs-only/inode.c:38:0:
/tmp/modconfig-cAothp/vmhgfs-only/inode.c: In function ‘HgfsPackSetattrRequest’:
/tmp/modconfig-cAothp/vmhgfs-only/./shared/compat_cred.h:43:29: error: request for member ‘val’ in something not a structure or union
 #define KUID2UID(kuid) (kuid.val)
                             ^
/tmp/modconfig-cAothp/vmhgfs-only/inode.c:520:27: note: in expansion of macro ‘KUID2UID’
          attrV2->userId = KUID2UID(iattr->ia_uid);
                           ^
/tmp/modconfig-cAothp/vmhgfs-only/./shared/compat_cred.h:44:29: error: request for member ‘val’ in something not a structure or union
 #define KGID2GID(kgid) (kgid.val)
                             ^
/tmp/modconfig-cAothp/vmhgfs-only/inode.c:526:28: note: in expansion of macro ‘KGID2GID’
          attrV2->groupId = KGID2GID(iattr->ia_gid);
                            ^
/tmp/modconfig-cAothp/vmhgfs-only/./shared/compat_cred.h:43:29: error: request for member ‘val’ in something not a structure or union
 #define KUID2UID(kuid) (kuid.val)
                             ^
/tmp/modconfig-cAothp/vmhgfs-only/inode.c:623:27: note: in expansion of macro ‘KUID2UID’
          attrV2->userId = KUID2UID(iattr->ia_uid);
                           ^
/tmp/modconfig-cAothp/vmhgfs-only/./shared/compat_cred.h:44:29: error: request for member ‘val’ in something not a structure or union
 #define KGID2GID(kgid) (kgid.val)
                             ^
/tmp/modconfig-cAothp/vmhgfs-only/inode.c:629:28: note: in expansion of macro ‘KGID2GID’
          attrV2->groupId = KGID2GID(iattr->ia_gid);
                            ^
scripts/Makefile.build:308: recipe for target '/tmp/modconfig-cAothp/vmhgfs-only/inode.o' failed
make[2]: *** [/tmp/modconfig-cAothp/vmhgfs-only/inode.o] Error 1
Makefile:1228: recipe for target '_module_/tmp/modconfig-cAothp/vmhgfs-only' failed
make[1]: *** [_module_/tmp/modconfig-cAothp/vmhgfs-only] Error 2make[1]: Leaving directory '/usr/src/linux-3.12.2-1-ARCH'
Makefile:130: recipe for target 'vmhgfs.ko' failed
make: *** [vmhgfs.ko] Error 2
make: Leaving directory '/tmp/modconfig-cAothp/vmhgfs-only'
```

I did some searching and found a couple stack overflow posts saying that this error means that you should use "->" instead of "."; I tried making that change myself and the error changed to:

```
/tmp/modconfig-9aRYHR/vmhgfs-only/./shared/compat_cred.h:43:29: error: invalid type argument of ‘->’ (have ‘kuid_t’)
 #define KUID2UID(kuid) (kuid->val)
                             ^
/tmp/modconfig-9aRYHR/vmhgfs-only/inode.c:517:27: note: in expansion of macro ‘KUID2UID’
          attrV2->userId = KUID2UID(iattr->ia_uid);
                           ^
/tmp/modconfig-9aRYHR/vmhgfs-only/./shared/compat_cred.h:44:29: error: invalid type argument of ‘->’ (have ‘kgid_t’)
 #define KGID2GID(kgid) (kgid->val)
                             ^
/tmp/modconfig-9aRYHR/vmhgfs-only/inode.c:523:28: note: in expansion of macro ‘KGID2GID’
          attrV2->groupId = KGID2GID(iattr->ia_gid);
                            ^
/tmp/modconfig-9aRYHR/vmhgfs-only/./shared/compat_cred.h:43:29: error: invalid type argument of ‘->’ (have ‘kuid_t’)
 #define KUID2UID(kuid) (kuid->val)
                             ^
/tmp/modconfig-9aRYHR/vmhgfs-only/inode.c:620:27: note: in expansion of macro ‘KUID2UID’
          attrV2->userId = KUID2UID(iattr->ia_uid);
                           ^
/tmp/modconfig-9aRYHR/vmhgfs-only/./shared/compat_cred.h:44:29: error: invalid type argument of ‘->’ (have ‘kgid_t’)
 #define KGID2GID(kgid) (kgid->val)
                             ^
/tmp/modconfig-9aRYHR/vmhgfs-only/inode.c:626:28: note: in expansion of macro ‘KGID2GID’
          attrV2->groupId = KGID2GID(iattr->ia_gid);
                            ^
```

Which (according to my searches) means that you should use "." instead of "->". My best guess is that `kgid` and `kuid` are getting passed in differently in different contexts, but I'm not that great with C; what do you think?
