### ISSUE TITLE
HGFS fails to compile on kernel 3.17.7

### ISSUE THREAD

**Issue by liayn** [rasa/vmware-tools-patches#17]
No solution yet to this problem

```
/tmp/modconfig-o3DxdS/vmhgfs-only/inode.c:1898:7: note: in expansion of macro ‘hlist_for_each_entry’
       hlist_for_each_entry(dentry,
       ^
In file included from include/linux/compiler-gcc.h:106:0,
                 from include/linux/compiler.h:54,
                 from include/uapi/linux/stddef.h:1,
                 from include/linux/stddef.h:4,
                 from ./include/uapi/linux/posix_types.h:4,
                 from include/uapi/linux/types.h:13,
                 from include/linux/types.h:5,
                 from /tmp/modconfig-o3DxdS/vmhgfs-only/./shared/driver-config.h:71,
                 from /tmp/modconfig-o3DxdS/vmhgfs-only/inode.c:26:
include/linux/compiler-gcc4.h:14:34: error: ‘struct dentry’ has no member named ‘d_alias’
 #define __compiler_offsetof(a,b) __builtin_offsetof(a,b)
                                  ^
```

In /usr/src/kernels/3.17.4-200.fc20.x86_64/include/linux/dcache.h the struct dentry still contains d_alias.

**Comment by rasa** [comment]
Fixed via #18

**Comment by sprossiter** [comment]
I'm getting a very similar error but on kernel 3.2.0-76 (Ubuntu 12.04 x64), with both VMWare Tools 9.9.0 (VMWare Player 7.0.0) and the older version (9.6?) on VMWare Player 6.0.3.

/tmp/modconfig-ESluHO/vmhgfs-only/inode.c: In function ‘HgfsPermission’:
/tmp/modconfig-ESluHO/vmhgfs-only/inode.c:1978:34: error: ‘struct dentry’ has no member named ‘d_alias’
/tmp/modconfig-ESluHO/vmhgfs-only/inode.c:1978:34: warning: initialisation from incompatible pointer type [enabled by default]
/tmp/modconfig-ESluHO/vmhgfs-only/inode.c:1978:34: warning: (near initialisation for ‘dentry’) [enabled by default]
/tmp/modconfig-ESluHO/vmhgfs-only/inode.c:1978:34: **error: ‘struct dentry’ has no member named ‘d_alias’**
  CC [M]  /tmp/modconfig-ESluHO/vmhgfs-only/request.o
make[2]: *** [/tmp/modconfig-ESluHO/vmhgfs-only/inode.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [_module_/tmp/modconfig-ESluHO/vmhgfs-only] Error 2
make[1]: Leaving directory `/usr/src/linux-headers-3.2.0-76-generic'
make: *** [vmhgfs.ko] Error 2
make: Leaving directory `/tmp/modconfig-ESluHO/vmhgfs-only'

Is the same patch (with suitably adjusted kernel version checks) appropriate here? Seems strange that it's in such an old kernel version and yet this bug is for 3.17.7. If you want me to raise a new issue let me know... (Also strange that doesn't seem known about from a Google given it's in a current Ubuntu 12.04 kernel...)

**Comment by rasa** [comment]
That is weird, as every `d_alias` reference has a kernel check around it. See https://github.com/rasa/vmware-tools-patches/search?q=d_alias

If you could gist the entire log, maybe we can see if a patch failed to apply.

**Comment by sprossiter** [comment]
Sorry, not sure I explained myself properly.

I'm having what seems to be the same issue on kernel 3.2.0-76, but the checks in the patch from this issue mean that the alternative code (with `d_u.d_alias`) is only used for kernels >= 3.17.7. I haven't tried to apply this patch because (a) the form of those checks means it won't do anything on 3.2.0; (b) I want to be sure that the problem (if it is one) with 3.2.0-76 is fixed by this change for 3.17.7.

Obviously I could change (a) manually myself and try to apply it, but I wanted to check first that the 3.17.7 fix is likely to be the right one in this case (and that there genuinely is an issue for this kernel version).

I also tried to go back to earlier kernel versions to absolutely check which one it failed after, but then I get problems that `vmware-config-tools.pl` can't find the kernel headers path. This seems similar to the issue at http://askubuntu.com/questions/40979, but there is no `/lib/modules/$(uname -r)/build` path in that case to apply the suggested fix. (That path only exists for the latest 3.2.0-76 kernel, not any older ones that I boot into.)

**Comment by rjoliver** [comment]
I had the exact same problem, except on a 32-bit system.  Falling back to 3.2.0-74, I was able to recompile VMware tools, including HGFS support, without incident.  I didn't try 3.2.0-75.

**Comment by sprossiter** [comment]
Yep, can confirm what rjoliver says,  and also that the vanilla 9.9.0 VMWare tools work fine on 3.2.0-75 as well. Tried at home (kernel 3.2.0-75) and builds fine. It is the upgrade to 3.2.0-76 where it fails.

(The headers path problem is, it seems, because I foolishly uninstalled the old kernel packages on my work PC, and tried to move back to an old kernel by reinstalling the kernel and headers packages. This seems to have left the `/lib/modules` folder for the re-installed kernel version in the strange state; if no-one here has an idea on how to fix that, I may add a question on SuperUser or similar...)

As a general question, are the bugs found/patched here being reported to VMWare, or is that deemed a futile exercise? (If there's one for 3.17.7 I can add to / copy that for this issue.)

**Comment by ocontant** [comment]
I'm having this problem on 3.18.3-201 on Fedora 21.  Is there a patch available?

**Comment by ocontant** [comment]
I followed this post and it worked for me : 
http://docs.kali.org/general-use/install-vmware-tools-kali-guest

**Comment by sprossiter** [comment]
@ocontant Um, this issue is precisely about a patch for this for kernels >= 3.17.7. The post you followed just applies that patch. My comments and those of @rjoliver were about the same issue on 3.2.0 kernels (in Ubuntu 12.04), which the patch doesn't (yet) work on.

**Comment by sprossiter** [comment]
> I also tried to go back to earlier kernel versions to absolutely check which one it failed after, but 
> then I get problems that vmware-config-tools.pl can't find the kernel headers path. This seems 
> similar to the issue at http://askubuntu.com/questions/40979, but there is no
> /lib/modules/$(uname -r)/build path in that case to apply the suggested fix. (That path only exists 
> for the latest 3.2.0-76 kernel, not any older ones that I boot into.)

That was because I only installed `linux-headers-3.2.0-75` and not `linux-headers-3.2.0-75-generic`. Doh. Now 'safely' back at 3.2.0-75.

**Comment by phs** [comment]
@liayn 's patch didn't work for me, but was very close.  Here's what I had to do: https://gist.github.com/phs/ffcb9f4d05311627d5e8

**Comment by sprossiter** [comment]
@phs Right, so you just implemented the same fix in the patch but 'directly' without the kernel-version-checking preprocessor statements (i.e., you're confirming that the fix for 3.17.7+ is appropriate for 3.2.0-76+; thanks). You seem surprised that the existing patch didn't work for you but that's what we've just been saying in the previous comments! I mean, that's what all these patches do: insert kernel version check preprocessor directives so that the changes are only applied to kernel versions that should get them. This one was set for 3.17.7+ (where the issue originally occurred) and so wouldn't change anything in 3.2.0.

Given that the fix 'universally' holds for 3.17.7+ and 3.2.0.76+, the real question is which exact kernel versions it applies to (and thus what the correct form of the revised `#if` statements should be). If the `d_alias` change has been put in 3.2.0-76+, has it also been put in recent versions of other 3.a.b kernels before 3.17.7? One would imagine yes since these releases (incrementing the 4th number) are normally 'bug release' security/stability fixes which need to apply everywhere they existed.  In either case the `#if` tests are complicated because the fix is only needed for 'bug releases' *within* `3.a.b` releases.

Unfortunately I'm not C++ / kernel source literate enough to know how to check these things and what syntax is accessible in the preprocessor directives; e.g., is there a KERNEL_VERSION alternative which allows you to specify the 'bug release' fourth number?

(P.S. Obviously the 'direct' fix without preprocessor directives will keep working on systems where the kernel doesn't change to a release where it doesn't apply.)

**Comment by pierrestone** [comment]
Hello,
I also have the d_alias issue on  kernel 3.2.0-76, but it's not clear for me where to apply the patch?

trace:
Using 2.6.x kernel build system.
make: Entering directory `/tmp/modconfig-WiLnkC/vmhgfs-only'
/usr/bin/make -C /lib/modules/3.2.0-76-virtual/build/include/.. SUBDIRS=$PWD SRCROOT=$PWD/. \
          MODULEBUILDDIR= modules
make[1]: Entering directory `/usr/src/linux-headers-3.2.0-76-virtual'
  CC [M]  /tmp/modconfig-WiLnkC/vmhgfs-only/backdoor.o
  CC [M]  /tmp/modconfig-WiLnkC/vmhgfs-only/backdoorGcc64.o
[..]
/tmp/modconfig-WiLnkC/vmhgfs-only/inode.c: In function ‘HgfsPermission’:
/tmp/modconfig-WiLnkC/vmhgfs-only/inode.c:1946:34: error: ‘struct dentry’ has no member named ‘d_alias’

also I'm on "virtual" headers, what's the differences with "generic" or without a postfix?
thanks

**Comment by Maxim-Filimonov** [comment]
Same problem on latest 14.04.02 ->  kernel 3.13.0-46 fails with this exact error.
Downgrade to 3.13.0-45 fixes it :\

**Comment by jverhoeven** [comment]
Same here as Maxim, kernel 3.13.0-46.

**Comment by vschoener** [comment]
Got same problem here.

/tmp/modconfig-mdE49U/vmhgfs-only/inode.c: In function ‘HgfsPermission’:
/tmp/modconfig-mdE49U/vmhgfs-only/inode.c:1978:34: error: ‘struct dentry’ has no member named ‘d_alias’
/tmp/modconfig-mdE49U/vmhgfs-only/inode.c:1978:34: warning: initialization from incompatible pointer type [enabled by default]
/tmp/modconfig-mdE49U/vmhgfs-only/inode.c:1978:34: warning: (near initialization for ‘dentry’) [enabled by default]
/tmp/modconfig-mdE49U/vmhgfs-only/inode.c:1978:34: error: ‘struct dentry’ has no member named ‘d_alias’

**Comment by LukeMauldin** [comment]
I am getting this same error on Ubuntu: Linux version 3.16.0-31-generic (buildd@batsu) (gcc version 4.9.1 (Ubuntu 4.9.1-16ubuntu6) ) #41-Ubuntu SMP Tue Feb 10 15:24:04 UTC 2015

**Comment by frol** [comment]
It seems that Ubuntu backported some features from 3.17+ to LTS kernels...

**Comment by rasa** [comment]
Fixed in https://github.com/rasa/vmware-tools-patches/commit/192e3b78b94cfa872d45043d671fe0cb4572b714#

**Comment by Maxim-Filimonov** [comment]
@rasa thx :+1:

**Comment by wiceywkus** [comment]
Config:
VMware Workstation 11: 11.1.0 build-2496824
Kernel: 3.16.0-33-generic

@rasa: Patch and your patch procedure worked for me!   Thank you! 
Kali's short procedure also worked: http://docs.kali.org/general-use/install-vmware-tools-kali-guest

**Comment by all3g** [comment]
When vmware-tools is installed on my PC, it shows me errors as follow:

```
root@kali:~# vmware-hgfsclient                                                                                                                                            
sharefoldes

root@kali:~# vmware-config-tools.pl -d --clobber-kernel-modules=vmhgfs
The module vmhgfs depends on vmci.  Because of this dependency, vmci has been 
added to the list of kernel modules to be overwritten by this installer.
......
......
make[1]: Entering directory `/usr/src/linux-headers-3.18.0-kali3-686-pae'
  CC [M]  /tmp/modconfig-ugqdQc/vmhgfs-only/backdoor.o
  CC [M]  /tmp/modconfig-ugqdQc/vmhgfs-only/backdoorGcc32.o
  CC [M]  /tmp/modconfig-ugqdQc/vmhgfs-only/bdhandler.o
  CC [M]  /tmp/modconfig-ugqdQc/vmhgfs-only/cpName.o
  CC [M]  /tmp/modconfig-ugqdQc/vmhgfs-only/cpNameLinux.o
  CC [M]  /tmp/modconfig-ugqdQc/vmhgfs-only/cpNameLite.o
  CC [M]  /tmp/modconfig-ugqdQc/vmhgfs-only/dentry.o
  CC [M]  /tmp/modconfig-ugqdQc/vmhgfs-only/dir.o
  CC [M]  /tmp/modconfig-ugqdQc/vmhgfs-only/file.o
  CC [M]  /tmp/modconfig-ugqdQc/vmhgfs-only/filesystem.o
  CC [M]  /tmp/modconfig-ugqdQc/vmhgfs-only/fsutil.o
  CC [M]  /tmp/modconfig-ugqdQc/vmhgfs-only/hgfsBd.o
  CC [M]  /tmp/modconfig-ugqdQc/vmhgfs-only/hgfsEscape.o
  CC [M]  /tmp/modconfig-ugqdQc/vmhgfs-only/hgfsUtil.o
  CC [M]  /tmp/modconfig-ugqdQc/vmhgfs-only/inode.o
  CC [M]  /tmp/modconfig-ugqdQc/vmhgfs-only/link.o
/tmp/modconfig-ugqdQc/vmhgfs-only/inode.c: In function ‘HgfsPermission’:
/tmp/modconfig-ugqdQc/vmhgfs-only/inode.c:1920:7: error: ‘struct dentry’ has no member named ‘d_alias’
/tmp/modconfig-ugqdQc/vmhgfs-only/inode.c:1920:7: warning: initialization from incompatible pointer type [enabled by default]
/tmp/modconfig-ugqdQc/vmhgfs-only/inode.c:1920:7: error: ‘struct dentry’ has no member named ‘d_alias’
/tmp/modconfig-ugqdQc/vmhgfs-only/inode.c:1920:7: error: ‘struct dentry’ has no member named ‘d_alias’
/tmp/modconfig-ugqdQc/vmhgfs-only/inode.c:1920:7: error: ‘struct dentry’ has no member named ‘d_alias’
/tmp/modconfig-ugqdQc/vmhgfs-only/inode.c:1920:7: error: ‘struct dentry’ has no member named ‘d_alias’
/tmp/modconfig-ugqdQc/vmhgfs-only/inode.c:1920:7: warning: initialization makes pointer from integer without a cast [enabled by default]
/tmp/modconfig-ugqdQc/vmhgfs-only/inode.c:1920:7: error: ‘struct dentry’ has no member named ‘d_alias’
......
......
```
Try [solutions](http://docs.kali.org/general-use/install-vmware-tools-kali-guest) from kali linux, and everything goes well.
```
root@kali:~# git clone https://github.com/rasa/vmware-tools-patches.git

root@kali:~# cd vmware-tools-patches/

root@kali:~/vmware-tools-patches# cp /media/cdrom/VMwareTools-9.9.0-2304977.tar.gz downloads/

root@kali:~/vmware-tools-patches# ls -l
total 72
-rw-r--r--  1 root root   31  Jul 24 18:09 CHANGELOG.md
-rwxr-xr-x  1 root root  955  Jul 24 18:09 compile.sh
-rw-r--r--  1 root root 4783  Jul 24 18:09 CONTRIBUTING.md
-rwxr-xr-x  1 root root 1137  Jul 24 18:09 download-patches.sh
drwxr-xr-x  2 root root 4096  Jul 24 18:12 downloads
-rwxr-xr-x  1 root root 3151  Jul 24 18:09 download-tools.sh
-rw-r--r--  1 root root 1085  Jul 24 18:09 LICENSE
drwxr-xr-x 11 root root 4096  Jul 24 18:09 patches
-rwxr-xr-x  1 root root 2217  Jul 24 18:09 patch-module.sh
-rwxr-xr-x  1 root root  781  Jul 24 18:09 patch.sh
-rw-r--r--  1 root root 7758  Jul 24 18:09 README.md
-rwxr-xr-x  1 root root  470  Jul 24 18:09 untar-all-and-patch.sh
-rwxr-xr-x  1 root root  280  Jul 24 18:09 untar-and-patch-and-compile.sh
-rwxr-xr-x  1 root root  225  Jul 24 18:09 untar-and-patch.sh
-rwxr-xr-x  1 root root  657  Jul 24 18:09 untar.sh
-rw-r--r--  1 root root   65  Jul 24 18:11 ~url.txt
root@kali:~/vmware-tools-patches# ./untar-and-patch-and-compile.sh 
untar.sh: Patching ./downloads/VMwareTools-9.9.0-2304977.tar.gz
.......
```

[mount sharefolder](http://pubs.vmware.com/workstation-9/index.jsp?topic=%2Fcom.vmware.ws.using.doc%2FGUID-AB5C80FE-9B8A-4899-8186-3DB8201B1758.html) as follow:
```
mount -t vmhgfs .host:/ /home/user1/shares
mount -t vmhgfs .host:/foo /tmp/foo
mount -t vmhgfs .host:/foo/bar /var/lib/bar
```
